// Mocks generated by Mockito 5.4.2 from annotations
// in fossil/test/onboarding_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i10;

import 'package:mastodon_api/src/core/language.dart' as _i15;
import 'package:mastodon_api/src/core/locale.dart' as _i6;
import 'package:mastodon_api/src/service/entities/account.dart' as _i7;
import 'package:mastodon_api/src/service/entities/account_preferences.dart'
    as _i17;
import 'package:mastodon_api/src/service/entities/empty.dart' as _i18;
import 'package:mastodon_api/src/service/entities/familiar_follower.dart'
    as _i16;
import 'package:mastodon_api/src/service/entities/featured_tag.dart' as _i12;
import 'package:mastodon_api/src/service/entities/relationship.dart' as _i14;
import 'package:mastodon_api/src/service/entities/report.dart' as _i20;
import 'package:mastodon_api/src/service/entities/report_category.dart' as _i21;
import 'package:mastodon_api/src/service/entities/status.dart' as _i11;
import 'package:mastodon_api/src/service/entities/tag.dart' as _i19;
import 'package:mastodon_api/src/service/entities/token.dart' as _i5;
import 'package:mastodon_api/src/service/entities/user_list.dart' as _i13;
import 'package:mastodon_api/src/service/response/mastodon_response.dart'
    as _i2;
import 'package:mastodon_api/src/service/v1/accounts/account_default_settings_param.dart'
    as _i8;
import 'package:mastodon_api/src/service/v1/accounts/account_profile_meta_param.dart'
    as _i9;
import 'package:mastodon_api/src/service/v1/accounts/accounts_v1_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMastodonResponse_0<D> extends _i1.SmartFake
    implements _i2.MastodonResponse<D> {
  _FakeMastodonResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountsV1Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountsV1Service extends _i1.Mock implements _i3.AccountsV1Service {
  @override
  _i4.Future<_i2.MastodonResponse<_i5.Token>> createAccount({
    required String? username,
    required String? email,
    required String? password,
    required bool? agreement,
    required _i6.Locale? locale,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [],
          {
            #username: username,
            #email: email,
            #password: password,
            #agreement: agreement,
            #locale: locale,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Token>>.value(
            _FakeMastodonResponse_0<_i5.Token>(
          this,
          Invocation.method(
            #createAccount,
            [],
            {
              #username: username,
              #email: email,
              #password: password,
              #agreement: agreement,
              #locale: locale,
              #reason: reason,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Token>>.value(
                _FakeMastodonResponse_0<_i5.Token>(
          this,
          Invocation.method(
            #createAccount,
            [],
            {
              #username: username,
              #email: email,
              #password: password,
              #agreement: agreement,
              #locale: locale,
              #reason: reason,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Token>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>> verifyAccountCredentials(
          {String? bearerToken}) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyAccountCredentials,
          [],
          {#bearerToken: bearerToken},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
            _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #verifyAccountCredentials,
            [],
            {#bearerToken: bearerToken},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #verifyAccountCredentials,
            [],
            {#bearerToken: bearerToken},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>> updateAccount({
    String? displayName,
    String? bio,
    bool? discoverable,
    bool? bot,
    bool? locked,
    _i8.AccountDefaultSettingsParam? defaultSettings,
    List<_i9.AccountProfileMetaParam>? profileMeta,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [],
          {
            #displayName: displayName,
            #bio: bio,
            #discoverable: discoverable,
            #bot: bot,
            #locked: locked,
            #defaultSettings: defaultSettings,
            #profileMeta: profileMeta,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
            _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #updateAccount,
            [],
            {
              #displayName: displayName,
              #bio: bio,
              #discoverable: discoverable,
              #bot: bot,
              #locked: locked,
              #defaultSettings: defaultSettings,
              #profileMeta: profileMeta,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #updateAccount,
            [],
            {
              #displayName: displayName,
              #bio: bio,
              #discoverable: discoverable,
              #bot: bot,
              #locked: locked,
              #defaultSettings: defaultSettings,
              #profileMeta: profileMeta,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>> updateAvatarImage(
          {required _i10.File? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAvatarImage,
          [],
          {#file: file},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
            _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #updateAvatarImage,
            [],
            {#file: file},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #updateAvatarImage,
            [],
            {#file: file},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>> updateHeaderImage(
          {required _i10.File? file}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHeaderImage,
          [],
          {#file: file},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
            _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #updateHeaderImage,
            [],
            {#file: file},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #updateHeaderImage,
            [],
            {#file: file},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>> lookupById(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupById,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
            _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #lookupById,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #lookupById,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>> lookupAccount(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupAccount,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
            _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #lookupAccount,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
          this,
          Invocation.method(
            #lookupAccount,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i11.Status>>> lookupStatuses({
    required String? accountId,
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    String? tagged,
    int? limit,
    bool? excludeReblogs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupStatuses,
          [],
          {
            #accountId: accountId,
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #tagged: tagged,
            #limit: limit,
            #excludeReblogs: excludeReblogs,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>.value(
            _FakeMastodonResponse_0<List<_i11.Status>>(
          this,
          Invocation.method(
            #lookupStatuses,
            [],
            {
              #accountId: accountId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #tagged: tagged,
              #limit: limit,
              #excludeReblogs: excludeReblogs,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>.value(
                _FakeMastodonResponse_0<List<_i11.Status>>(
          this,
          Invocation.method(
            #lookupStatuses,
            [],
            {
              #accountId: accountId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #tagged: tagged,
              #limit: limit,
              #excludeReblogs: excludeReblogs,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> lookupFollowers({
    required String? accountId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFollowers,
          [],
          {
            #accountId: accountId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFollowers,
            [],
            {
              #accountId: accountId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFollowers,
            [],
            {
              #accountId: accountId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> lookupFollowings({
    required String? accountId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFollowings,
          [],
          {
            #accountId: accountId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFollowings,
            [],
            {
              #accountId: accountId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFollowings,
            [],
            {
              #accountId: accountId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>> lookupFeaturedTags(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFeaturedTags,
          [],
          {#accountId: accountId},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>.value(
                _FakeMastodonResponse_0<List<_i12.FeaturedTag>>(
          this,
          Invocation.method(
            #lookupFeaturedTags,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>.value(
                _FakeMastodonResponse_0<List<_i12.FeaturedTag>>(
          this,
          Invocation.method(
            #lookupFeaturedTags,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i13.UserList>>> lookupContainedLists(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupContainedLists,
          [],
          {#accountId: accountId},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i13.UserList>>>.value(
                _FakeMastodonResponse_0<List<_i13.UserList>>(
          this,
          Invocation.method(
            #lookupContainedLists,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i13.UserList>>>.value(
                _FakeMastodonResponse_0<List<_i13.UserList>>(
          this,
          Invocation.method(
            #lookupContainedLists,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i13.UserList>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> createFollow({
    required String? accountId,
    bool? receiveReblogs,
    bool? receiveNotifications,
    List<_i15.Language>? filteringLanguages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFollow,
          [],
          {
            #accountId: accountId,
            #receiveReblogs: receiveReblogs,
            #receiveNotifications: receiveNotifications,
            #filteringLanguages: filteringLanguages,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createFollow,
            [],
            {
              #accountId: accountId,
              #receiveReblogs: receiveReblogs,
              #receiveNotifications: receiveNotifications,
              #filteringLanguages: filteringLanguages,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createFollow,
            [],
            {
              #accountId: accountId,
              #receiveReblogs: receiveReblogs,
              #receiveNotifications: receiveNotifications,
              #filteringLanguages: filteringLanguages,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> destroyFollow(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFollow,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFollow,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFollow,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> destroyFollower(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFollower,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFollower,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFollower,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> createBlock(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBlock,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createBlock,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createBlock,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> destroyBlock(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyBlock,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyBlock,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyBlock,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> createMute({
    required String? accountId,
    bool? includeNotifications,
    Duration? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMute,
          [],
          {
            #accountId: accountId,
            #includeNotifications: includeNotifications,
            #duration: duration,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createMute,
            [],
            {
              #accountId: accountId,
              #includeNotifications: includeNotifications,
              #duration: duration,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createMute,
            [],
            {
              #accountId: accountId,
              #includeNotifications: includeNotifications,
              #duration: duration,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> destroyMute(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyMute,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyMute,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyMute,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> createFeaturedProfile(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFeaturedProfile,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createFeaturedProfile,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createFeaturedProfile,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> destroyFeaturedProfile(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFeaturedProfile,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFeaturedProfile,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFeaturedProfile,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> updatePrivateComment({
    required String? accountId,
    String? text = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrivateComment,
          [],
          {
            #accountId: accountId,
            #text: text,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #updatePrivateComment,
            [],
            {
              #accountId: accountId,
              #text: text,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #updatePrivateComment,
            [],
            {
              #accountId: accountId,
              #text: text,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i14.Relationship>>> lookupRelationships(
          {required List<String>? accountIds}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupRelationships,
          [],
          {#accountIds: accountIds},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i14.Relationship>>>.value(
                _FakeMastodonResponse_0<List<_i14.Relationship>>(
          this,
          Invocation.method(
            #lookupRelationships,
            [],
            {#accountIds: accountIds},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i14.Relationship>>>.value(
                _FakeMastodonResponse_0<List<_i14.Relationship>>(
          this,
          Invocation.method(
            #lookupRelationships,
            [],
            {#accountIds: accountIds},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i14.Relationship>>>);

  @override
  _i4.Future<
      _i2
      .MastodonResponse<List<_i16.FamiliarFollower>>> lookupFamiliarFollowers(
          {required List<String>? accountIds}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFamiliarFollowers,
          [],
          {#accountIds: accountIds},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i16.FamiliarFollower>>>.value(
                _FakeMastodonResponse_0<List<_i16.FamiliarFollower>>(
          this,
          Invocation.method(
            #lookupFamiliarFollowers,
            [],
            {#accountIds: accountIds},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i16.FamiliarFollower>>>.value(
                _FakeMastodonResponse_0<List<_i16.FamiliarFollower>>(
          this,
          Invocation.method(
            #lookupFamiliarFollowers,
            [],
            {#accountIds: accountIds},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i16.FamiliarFollower>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> searchAccounts({
    required String? query,
    int? limit,
    bool? resolveWithWebFinger,
    bool? onlyFollowings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAccounts,
          [],
          {
            #query: query,
            #limit: limit,
            #resolveWithWebFinger: resolveWithWebFinger,
            #onlyFollowings: onlyFollowings,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #searchAccounts,
            [],
            {
              #query: query,
              #limit: limit,
              #resolveWithWebFinger: resolveWithWebFinger,
              #onlyFollowings: onlyFollowings,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #searchAccounts,
            [],
            {
              #query: query,
              #limit: limit,
              #resolveWithWebFinger: resolveWithWebFinger,
              #onlyFollowings: onlyFollowings,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Account>>
      lookupAccountFromWebFingerAddress({
    required String? accountIdentifier,
    bool? skipWebFinger,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #lookupAccountFromWebFingerAddress,
              [],
              {
                #accountIdentifier: accountIdentifier,
                #skipWebFinger: skipWebFinger,
              },
            ),
            returnValue: _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                _FakeMastodonResponse_0<_i7.Account>(
              this,
              Invocation.method(
                #lookupAccountFromWebFingerAddress,
                [],
                {
                  #accountIdentifier: accountIdentifier,
                  #skipWebFinger: skipWebFinger,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.MastodonResponse<_i7.Account>>.value(
                    _FakeMastodonResponse_0<_i7.Account>(
              this,
              Invocation.method(
                #lookupAccountFromWebFingerAddress,
                [],
                {
                  #accountIdentifier: accountIdentifier,
                  #skipWebFinger: skipWebFinger,
                },
              ),
            )),
          ) as _i4.Future<_i2.MastodonResponse<_i7.Account>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i17.AccountPreferences>>
      lookupPreferences() => (super.noSuchMethod(
            Invocation.method(
              #lookupPreferences,
              [],
            ),
            returnValue:
                _i4.Future<_i2.MastodonResponse<_i17.AccountPreferences>>.value(
                    _FakeMastodonResponse_0<_i17.AccountPreferences>(
              this,
              Invocation.method(
                #lookupPreferences,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.MastodonResponse<_i17.AccountPreferences>>.value(
                    _FakeMastodonResponse_0<_i17.AccountPreferences>(
              this,
              Invocation.method(
                #lookupPreferences,
                [],
              ),
            )),
          ) as _i4.Future<_i2.MastodonResponse<_i17.AccountPreferences>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>
      lookupOwnedFeaturedTags() => (super.noSuchMethod(
            Invocation.method(
              #lookupOwnedFeaturedTags,
              [],
            ),
            returnValue:
                _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>.value(
                    _FakeMastodonResponse_0<List<_i12.FeaturedTag>>(
              this,
              Invocation.method(
                #lookupOwnedFeaturedTags,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>.value(
                    _FakeMastodonResponse_0<List<_i12.FeaturedTag>>(
              this,
              Invocation.method(
                #lookupOwnedFeaturedTags,
                [],
              ),
            )),
          ) as _i4.Future<_i2.MastodonResponse<List<_i12.FeaturedTag>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i12.FeaturedTag>> createFeaturedTag(
          {required String? tagName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFeaturedTag,
          [],
          {#tagName: tagName},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i12.FeaturedTag>>.value(
            _FakeMastodonResponse_0<_i12.FeaturedTag>(
          this,
          Invocation.method(
            #createFeaturedTag,
            [],
            {#tagName: tagName},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i12.FeaturedTag>>.value(
                _FakeMastodonResponse_0<_i12.FeaturedTag>(
          this,
          Invocation.method(
            #createFeaturedTag,
            [],
            {#tagName: tagName},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i12.FeaturedTag>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i18.Empty>> destroyFeaturedTag(
          {required String? tagId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFeaturedTag,
          [],
          {#tagId: tagId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
            _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #destroyFeaturedTag,
            [],
            {#tagId: tagId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
                _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #destroyFeaturedTag,
            [],
            {#tagId: tagId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i18.Empty>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>> lookupSuggestedTags() =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupSuggestedTags,
          [],
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>>.value(
            _FakeMastodonResponse_0<List<_i19.Tag>>(
          this,
          Invocation.method(
            #lookupSuggestedTags,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>>.value(
                _FakeMastodonResponse_0<List<_i19.Tag>>(
          this,
          Invocation.method(
            #lookupSuggestedTags,
            [],
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>> lookupFollowedTags(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFollowedTags,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>>.value(
            _FakeMastodonResponse_0<List<_i19.Tag>>(
          this,
          Invocation.method(
            #lookupFollowedTags,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>>.value(
                _FakeMastodonResponse_0<List<_i19.Tag>>(
          this,
          Invocation.method(
            #lookupFollowedTags,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i19.Tag>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i18.Empty>> destroyFollowSuggestion(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFollowSuggestion,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
            _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #destroyFollowSuggestion,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
                _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #destroyFollowSuggestion,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i18.Empty>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i19.Tag>> lookupTag(
          {required String? tagId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupTag,
          [],
          {#tagId: tagId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i19.Tag>>.value(
            _FakeMastodonResponse_0<_i19.Tag>(
          this,
          Invocation.method(
            #lookupTag,
            [],
            {#tagId: tagId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i19.Tag>>.value(
                _FakeMastodonResponse_0<_i19.Tag>(
          this,
          Invocation.method(
            #lookupTag,
            [],
            {#tagId: tagId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i19.Tag>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i19.Tag>> createFollowingTag(
          {required String? tagId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFollowingTag,
          [],
          {#tagId: tagId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i19.Tag>>.value(
            _FakeMastodonResponse_0<_i19.Tag>(
          this,
          Invocation.method(
            #createFollowingTag,
            [],
            {#tagId: tagId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i19.Tag>>.value(
                _FakeMastodonResponse_0<_i19.Tag>(
          this,
          Invocation.method(
            #createFollowingTag,
            [],
            {#tagId: tagId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i19.Tag>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i19.Tag>> destroyFollowingTag(
          {required String? tagId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFollowingTag,
          [],
          {#tagId: tagId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i19.Tag>>.value(
            _FakeMastodonResponse_0<_i19.Tag>(
          this,
          Invocation.method(
            #destroyFollowingTag,
            [],
            {#tagId: tagId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i19.Tag>>.value(
                _FakeMastodonResponse_0<_i19.Tag>(
          this,
          Invocation.method(
            #destroyFollowingTag,
            [],
            {#tagId: tagId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i19.Tag>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i20.Report>> createReport({
    required String? accountId,
    String? reason,
    bool? forward,
    _i21.ReportCategory? category,
    List<String>? statusIds,
    List<String>? ruleIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReport,
          [],
          {
            #accountId: accountId,
            #reason: reason,
            #forward: forward,
            #category: category,
            #statusIds: statusIds,
            #ruleIds: ruleIds,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i20.Report>>.value(
            _FakeMastodonResponse_0<_i20.Report>(
          this,
          Invocation.method(
            #createReport,
            [],
            {
              #accountId: accountId,
              #reason: reason,
              #forward: forward,
              #category: category,
              #statusIds: statusIds,
              #ruleIds: ruleIds,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i20.Report>>.value(
                _FakeMastodonResponse_0<_i20.Report>(
          this,
          Invocation.method(
            #createReport,
            [],
            {
              #accountId: accountId,
              #reason: reason,
              #forward: forward,
              #category: category,
              #statusIds: statusIds,
              #ruleIds: ruleIds,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i20.Report>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> lookupFeaturedProfiles(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFeaturedProfiles,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFeaturedProfiles,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFeaturedProfiles,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> lookupMutedAccounts(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupMutedAccounts,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupMutedAccounts,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupMutedAccounts,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i11.Status>>> lookupFavouritedStatuses(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFavouritedStatuses,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>.value(
            _FakeMastodonResponse_0<List<_i11.Status>>(
          this,
          Invocation.method(
            #lookupFavouritedStatuses,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>.value(
                _FakeMastodonResponse_0<List<_i11.Status>>(
          this,
          Invocation.method(
            #lookupFavouritedStatuses,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> lookupBlockedAccounts(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupBlockedAccounts,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupBlockedAccounts,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupBlockedAccounts,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i11.Status>>> lookupBookmarkedStatuses(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupBookmarkedStatuses,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>.value(
            _FakeMastodonResponse_0<List<_i11.Status>>(
          this,
          Invocation.method(
            #lookupBookmarkedStatuses,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>.value(
                _FakeMastodonResponse_0<List<_i11.Status>>(
          this,
          Invocation.method(
            #lookupBookmarkedStatuses,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i11.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<String>>> lookupBlockedDomains(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupBlockedDomains,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<String>>>.value(
            _FakeMastodonResponse_0<List<String>>(
          this,
          Invocation.method(
            #lookupBlockedDomains,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<String>>>.value(
                _FakeMastodonResponse_0<List<String>>(
          this,
          Invocation.method(
            #lookupBlockedDomains,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<String>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i18.Empty>> createBlockedDomain(
          {required String? domainName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBlockedDomain,
          [],
          {#domainName: domainName},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
            _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #createBlockedDomain,
            [],
            {#domainName: domainName},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
                _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #createBlockedDomain,
            [],
            {#domainName: domainName},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i18.Empty>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i18.Empty>> destroyBlockedDomain(
          {required String? domainName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyBlockedDomain,
          [],
          {#domainName: domainName},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
            _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #destroyBlockedDomain,
            [],
            {#domainName: domainName},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i18.Empty>>.value(
                _FakeMastodonResponse_0<_i18.Empty>(
          this,
          Invocation.method(
            #destroyBlockedDomain,
            [],
            {#domainName: domainName},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i18.Empty>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i7.Account>>> lookupFollowRequests(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFollowRequests,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
            _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFollowRequests,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>.value(
                _FakeMastodonResponse_0<List<_i7.Account>>(
          this,
          Invocation.method(
            #lookupFollowRequests,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i7.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> createFollower(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFollower,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createFollower,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #createFollower,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i14.Relationship>> destroyFollowRequest(
          {required String? accountId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFollowRequest,
          [],
          {#accountId: accountId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
            _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFollowRequest,
            [],
            {#accountId: accountId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i14.Relationship>>.value(
                _FakeMastodonResponse_0<_i14.Relationship>(
          this,
          Invocation.method(
            #destroyFollowRequest,
            [],
            {#accountId: accountId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i14.Relationship>>);
}
