// Mocks generated by Mockito 5.4.2 from annotations
// in fossil/test/timeline_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mastodon_api/src/core/language.dart' as _i12;
import 'package:mastodon_api/src/core/visibility.dart' as _i11;
import 'package:mastodon_api/src/service/entities/account.dart' as _i18;
import 'package:mastodon_api/src/service/entities/conversation.dart' as _i6;
import 'package:mastodon_api/src/service/entities/empty.dart' as _i7;
import 'package:mastodon_api/src/service/entities/notification_snapshot.dart'
    as _i9;
import 'package:mastodon_api/src/service/entities/poll.dart' as _i16;
import 'package:mastodon_api/src/service/entities/scheduled_status.dart'
    as _i19;
import 'package:mastodon_api/src/service/entities/status.dart' as _i5;
import 'package:mastodon_api/src/service/entities/status_context.dart' as _i17;
import 'package:mastodon_api/src/service/entities/status_edit.dart' as _i14;
import 'package:mastodon_api/src/service/entities/status_snapshot.dart' as _i8;
import 'package:mastodon_api/src/service/entities/status_source.dart' as _i15;
import 'package:mastodon_api/src/service/response/mastodon_response.dart'
    as _i2;
import 'package:mastodon_api/src/service/v1/statuses/status_poll_param.dart'
    as _i13;
import 'package:mastodon_api/src/service/v1/statuses/statuses_v1_service.dart'
    as _i10;
import 'package:mastodon_api/src/service/v1/timelines/timelines_v1_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMastodonResponse_0<D> extends _i1.SmartFake
    implements _i2.MastodonResponse<D> {
  _FakeMastodonResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimelinesV1Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelinesV1Service extends _i1.Mock
    implements _i3.TimelinesV1Service {
  @override
  _i4.Future<_i2.MastodonResponse<List<_i5.Status>>> lookupPublicTimeline({
    bool? onlyLocal,
    bool? onlyRemote,
    bool? onlyMedia,
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupPublicTimeline,
          [],
          {
            #onlyLocal: onlyLocal,
            #onlyRemote: onlyRemote,
            #onlyMedia: onlyMedia,
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
            _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupPublicTimeline,
            [],
            {
              #onlyLocal: onlyLocal,
              #onlyRemote: onlyRemote,
              #onlyMedia: onlyMedia,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
                _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupPublicTimeline,
            [],
            {
              #onlyLocal: onlyLocal,
              #onlyRemote: onlyRemote,
              #onlyMedia: onlyMedia,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i5.Status>>> lookupTimelineByHashtag({
    required String? hashtag,
    bool? onlyLocal,
    bool? onlyRemote,
    bool? onlyMedia,
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupTimelineByHashtag,
          [],
          {
            #hashtag: hashtag,
            #onlyLocal: onlyLocal,
            #onlyRemote: onlyRemote,
            #onlyMedia: onlyMedia,
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
            _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupTimelineByHashtag,
            [],
            {
              #hashtag: hashtag,
              #onlyLocal: onlyLocal,
              #onlyRemote: onlyRemote,
              #onlyMedia: onlyMedia,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
                _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupTimelineByHashtag,
            [],
            {
              #hashtag: hashtag,
              #onlyLocal: onlyLocal,
              #onlyRemote: onlyRemote,
              #onlyMedia: onlyMedia,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i5.Status>>> lookupHomeTimeline({
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupHomeTimeline,
          [],
          {
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
            _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupHomeTimeline,
            [],
            {
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
                _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupHomeTimeline,
            [],
            {
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i5.Status>>> lookupListTimeline({
    required String? listId,
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupListTimeline,
          [],
          {
            #listId: listId,
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
            _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupListTimeline,
            [],
            {
              #listId: listId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>.value(
                _FakeMastodonResponse_0<List<_i5.Status>>(
          this,
          Invocation.method(
            #lookupListTimeline,
            [],
            {
              #listId: listId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i5.Status>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i6.Conversation>>> lookupConversations(
          {int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupConversations,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i6.Conversation>>>.value(
                _FakeMastodonResponse_0<List<_i6.Conversation>>(
          this,
          Invocation.method(
            #lookupConversations,
            [],
            {#limit: limit},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i6.Conversation>>>.value(
                _FakeMastodonResponse_0<List<_i6.Conversation>>(
          this,
          Invocation.method(
            #lookupConversations,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i6.Conversation>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Empty>> destroyConversation(
          {required String? conversationId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyConversation,
          [],
          {#conversationId: conversationId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Empty>>.value(
            _FakeMastodonResponse_0<_i7.Empty>(
          this,
          Invocation.method(
            #destroyConversation,
            [],
            {#conversationId: conversationId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Empty>>.value(
                _FakeMastodonResponse_0<_i7.Empty>(
          this,
          Invocation.method(
            #destroyConversation,
            [],
            {#conversationId: conversationId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Empty>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i6.Conversation>>
      createMarkConversationAsRead({required String? conversationId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #createMarkConversationAsRead,
              [],
              {#conversationId: conversationId},
            ),
            returnValue:
                _i4.Future<_i2.MastodonResponse<_i6.Conversation>>.value(
                    _FakeMastodonResponse_0<_i6.Conversation>(
              this,
              Invocation.method(
                #createMarkConversationAsRead,
                [],
                {#conversationId: conversationId},
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.MastodonResponse<_i6.Conversation>>.value(
                    _FakeMastodonResponse_0<_i6.Conversation>(
              this,
              Invocation.method(
                #createMarkConversationAsRead,
                [],
                {#conversationId: conversationId},
              ),
            )),
          ) as _i4.Future<_i2.MastodonResponse<_i6.Conversation>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>> lookupStatusSnapshot() =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupStatusSnapshot,
          [],
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>>.value(
            _FakeMastodonResponse_0<_i8.StatusSnapshot>(
          this,
          Invocation.method(
            #lookupStatusSnapshot,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>>.value(
                _FakeMastodonResponse_0<_i8.StatusSnapshot>(
          this,
          Invocation.method(
            #lookupStatusSnapshot,
            [],
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>
      lookupNotificationSnapshot() => (super.noSuchMethod(
            Invocation.method(
              #lookupNotificationSnapshot,
              [],
            ),
            returnValue: _i4
                .Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>.value(
                _FakeMastodonResponse_0<_i9.NotificationSnapshot>(
              this,
              Invocation.method(
                #lookupNotificationSnapshot,
                [],
              ),
            )),
            returnValueForMissingStub: _i4
                .Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>.value(
                _FakeMastodonResponse_0<_i9.NotificationSnapshot>(
              this,
              Invocation.method(
                #lookupNotificationSnapshot,
                [],
              ),
            )),
          ) as _i4.Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>> createStatusSnapshot(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStatusSnapshot,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>>.value(
            _FakeMastodonResponse_0<_i8.StatusSnapshot>(
          this,
          Invocation.method(
            #createStatusSnapshot,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>>.value(
                _FakeMastodonResponse_0<_i8.StatusSnapshot>(
          this,
          Invocation.method(
            #createStatusSnapshot,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i8.StatusSnapshot>>);

  @override
  _i4.Future<
      _i2
      .MastodonResponse<_i9.NotificationSnapshot>> createNotificationSnapshot(
          {required String? notificationId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNotificationSnapshot,
          [],
          {#notificationId: notificationId},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>.value(
                _FakeMastodonResponse_0<_i9.NotificationSnapshot>(
          this,
          Invocation.method(
            #createNotificationSnapshot,
            [],
            {#notificationId: notificationId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>.value(
                _FakeMastodonResponse_0<_i9.NotificationSnapshot>(
          this,
          Invocation.method(
            #createNotificationSnapshot,
            [],
            {#notificationId: notificationId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i9.NotificationSnapshot>>);
}

/// A class which mocks [StatusesV1Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatusesV1Service extends _i1.Mock implements _i10.StatusesV1Service {
  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> createStatus({
    required String? text,
    String? spoilerText,
    String? inReplyToStatusId,
    bool? sensitive,
    _i11.Visibility? visibility,
    _i12.Language? language,
    List<String>? mediaIds,
    _i13.StatusPollParam? poll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStatus,
          [],
          {
            #text: text,
            #spoilerText: spoilerText,
            #inReplyToStatusId: inReplyToStatusId,
            #sensitive: sensitive,
            #visibility: visibility,
            #language: language,
            #mediaIds: mediaIds,
            #poll: poll,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createStatus,
            [],
            {
              #text: text,
              #spoilerText: spoilerText,
              #inReplyToStatusId: inReplyToStatusId,
              #sensitive: sensitive,
              #visibility: visibility,
              #language: language,
              #mediaIds: mediaIds,
              #poll: poll,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createStatus,
            [],
            {
              #text: text,
              #spoilerText: spoilerText,
              #inReplyToStatusId: inReplyToStatusId,
              #sensitive: sensitive,
              #visibility: visibility,
              #language: language,
              #mediaIds: mediaIds,
              #poll: poll,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> destroyStatus(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyStatus,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyStatus,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyStatus,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> updateStatus({
    required String? statusId,
    required String? text,
    String? spoilerText,
    bool? sensitive,
    _i12.Language? language,
    List<String>? mediaIds,
    _i13.StatusPollParam? poll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [],
          {
            #statusId: statusId,
            #text: text,
            #spoilerText: spoilerText,
            #sensitive: sensitive,
            #language: language,
            #mediaIds: mediaIds,
            #poll: poll,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #updateStatus,
            [],
            {
              #statusId: statusId,
              #text: text,
              #spoilerText: spoilerText,
              #sensitive: sensitive,
              #language: language,
              #mediaIds: mediaIds,
              #poll: poll,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #updateStatus,
            [],
            {
              #statusId: statusId,
              #text: text,
              #spoilerText: spoilerText,
              #sensitive: sensitive,
              #language: language,
              #mediaIds: mediaIds,
              #poll: poll,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i14.StatusEdit>>> lookupEditHistory(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupEditHistory,
          [],
          {#statusId: statusId},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i14.StatusEdit>>>.value(
                _FakeMastodonResponse_0<List<_i14.StatusEdit>>(
          this,
          Invocation.method(
            #lookupEditHistory,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i14.StatusEdit>>>.value(
                _FakeMastodonResponse_0<List<_i14.StatusEdit>>(
          this,
          Invocation.method(
            #lookupEditHistory,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i14.StatusEdit>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i15.StatusSource>> lookupEditableSource(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupEditableSource,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i15.StatusSource>>.value(
            _FakeMastodonResponse_0<_i15.StatusSource>(
          this,
          Invocation.method(
            #lookupEditableSource,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i15.StatusSource>>.value(
                _FakeMastodonResponse_0<_i15.StatusSource>(
          this,
          Invocation.method(
            #lookupEditableSource,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i15.StatusSource>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i16.Poll>> lookupPollById(
          {required String? pollId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupPollById,
          [],
          {#pollId: pollId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
            _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #lookupPollById,
            [],
            {#pollId: pollId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
                _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #lookupPollById,
            [],
            {#pollId: pollId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i16.Poll>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i16.Poll>> lookupPoll(
          {required String? pollId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupPoll,
          [],
          {#pollId: pollId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
            _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #lookupPoll,
            [],
            {#pollId: pollId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
                _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #lookupPoll,
            [],
            {#pollId: pollId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i16.Poll>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i16.Poll>> createVote({
    required String? pollId,
    required int? choice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVote,
          [],
          {
            #pollId: pollId,
            #choice: choice,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
            _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #createVote,
            [],
            {
              #pollId: pollId,
              #choice: choice,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
                _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #createVote,
            [],
            {
              #pollId: pollId,
              #choice: choice,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i16.Poll>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i16.Poll>> createVotes({
    required String? pollId,
    required List<int>? choices,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVotes,
          [],
          {
            #pollId: pollId,
            #choices: choices,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
            _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #createVotes,
            [],
            {
              #pollId: pollId,
              #choices: choices,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i16.Poll>>.value(
                _FakeMastodonResponse_0<_i16.Poll>(
          this,
          Invocation.method(
            #createVotes,
            [],
            {
              #pollId: pollId,
              #choices: choices,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i16.Poll>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> lookupById(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupById,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #lookupById,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #lookupById,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> lookupStatus(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupStatus,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #lookupStatus,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #lookupStatus,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i17.StatusContext>> lookupStatusContext(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupStatusContext,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i17.StatusContext>>.value(
            _FakeMastodonResponse_0<_i17.StatusContext>(
          this,
          Invocation.method(
            #lookupStatusContext,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i17.StatusContext>>.value(
                _FakeMastodonResponse_0<_i17.StatusContext>(
          this,
          Invocation.method(
            #lookupStatusContext,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i17.StatusContext>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i18.Account>>> lookupRebloggedUsers({
    required String? statusId,
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupRebloggedUsers,
          [],
          {
            #statusId: statusId,
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i18.Account>>>.value(
            _FakeMastodonResponse_0<List<_i18.Account>>(
          this,
          Invocation.method(
            #lookupRebloggedUsers,
            [],
            {
              #statusId: statusId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i18.Account>>>.value(
                _FakeMastodonResponse_0<List<_i18.Account>>(
          this,
          Invocation.method(
            #lookupRebloggedUsers,
            [],
            {
              #statusId: statusId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i18.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<List<_i18.Account>>> lookupFavouritedUsers({
    required String? statusId,
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupFavouritedUsers,
          [],
          {
            #statusId: statusId,
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<List<_i18.Account>>>.value(
            _FakeMastodonResponse_0<List<_i18.Account>>(
          this,
          Invocation.method(
            #lookupFavouritedUsers,
            [],
            {
              #statusId: statusId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i18.Account>>>.value(
                _FakeMastodonResponse_0<List<_i18.Account>>(
          this,
          Invocation.method(
            #lookupFavouritedUsers,
            [],
            {
              #statusId: statusId,
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i18.Account>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> createFavourite(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFavourite,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createFavourite,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createFavourite,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> destroyFavourite(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyFavourite,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyFavourite,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyFavourite,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> createReblog(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReblog,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createReblog,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createReblog,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> destroyReblog(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyReblog,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyReblog,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyReblog,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> createBookmark(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookmark,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createBookmark,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createBookmark,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> destroyBookmark(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyBookmark,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyBookmark,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyBookmark,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> createMute(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMute,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createMute,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createMute,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> destroyMute(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyMute,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyMute,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyMute,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> createPinnedStatus(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPinnedStatus,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createPinnedStatus,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #createPinnedStatus,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i5.Status>> destroyPinnedStatus(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyPinnedStatus,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
            _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyPinnedStatus,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i5.Status>>.value(
                _FakeMastodonResponse_0<_i5.Status>(
          this,
          Invocation.method(
            #destroyPinnedStatus,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i5.Status>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>> createScheduledStatus({
    required String? text,
    required DateTime? schedule,
    String? spoilerText,
    String? inReplyToStatusId,
    bool? sensitive,
    _i11.Visibility? visibility,
    _i12.Language? language,
    List<String>? mediaIds,
    _i13.StatusPollParam? poll,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScheduledStatus,
          [],
          {
            #text: text,
            #schedule: schedule,
            #spoilerText: spoilerText,
            #inReplyToStatusId: inReplyToStatusId,
            #sensitive: sensitive,
            #visibility: visibility,
            #language: language,
            #mediaIds: mediaIds,
            #poll: poll,
          },
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>.value(
                _FakeMastodonResponse_0<_i19.ScheduledStatus>(
          this,
          Invocation.method(
            #createScheduledStatus,
            [],
            {
              #text: text,
              #schedule: schedule,
              #spoilerText: spoilerText,
              #inReplyToStatusId: inReplyToStatusId,
              #sensitive: sensitive,
              #visibility: visibility,
              #language: language,
              #mediaIds: mediaIds,
              #poll: poll,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>.value(
                _FakeMastodonResponse_0<_i19.ScheduledStatus>(
          this,
          Invocation.method(
            #createScheduledStatus,
            [],
            {
              #text: text,
              #schedule: schedule,
              #spoilerText: spoilerText,
              #inReplyToStatusId: inReplyToStatusId,
              #sensitive: sensitive,
              #visibility: visibility,
              #language: language,
              #mediaIds: mediaIds,
              #poll: poll,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>);

  @override
  _i4.Future<
      _i2
      .MastodonResponse<List<_i19.ScheduledStatus>>> lookupScheduledStatuses({
    String? maxStatusId,
    String? minStatusId,
    String? sinceStatusId,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupScheduledStatuses,
          [],
          {
            #maxStatusId: maxStatusId,
            #minStatusId: minStatusId,
            #sinceStatusId: sinceStatusId,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<List<_i19.ScheduledStatus>>>.value(
                _FakeMastodonResponse_0<List<_i19.ScheduledStatus>>(
          this,
          Invocation.method(
            #lookupScheduledStatuses,
            [],
            {
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<List<_i19.ScheduledStatus>>>.value(
                _FakeMastodonResponse_0<List<_i19.ScheduledStatus>>(
          this,
          Invocation.method(
            #lookupScheduledStatuses,
            [],
            {
              #maxStatusId: maxStatusId,
              #minStatusId: minStatusId,
              #sinceStatusId: sinceStatusId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<List<_i19.ScheduledStatus>>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>> lookupScheduledStatus(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupScheduledStatus,
          [],
          {#statusId: statusId},
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>.value(
                _FakeMastodonResponse_0<_i19.ScheduledStatus>(
          this,
          Invocation.method(
            #lookupScheduledStatus,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>.value(
                _FakeMastodonResponse_0<_i19.ScheduledStatus>(
          this,
          Invocation.method(
            #lookupScheduledStatus,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>> updateScheduledStatus({
    required String? statusId,
    required DateTime? schedule,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScheduledStatus,
          [],
          {
            #statusId: statusId,
            #schedule: schedule,
          },
        ),
        returnValue:
            _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>.value(
                _FakeMastodonResponse_0<_i19.ScheduledStatus>(
          this,
          Invocation.method(
            #updateScheduledStatus,
            [],
            {
              #statusId: statusId,
              #schedule: schedule,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>.value(
                _FakeMastodonResponse_0<_i19.ScheduledStatus>(
          this,
          Invocation.method(
            #updateScheduledStatus,
            [],
            {
              #statusId: statusId,
              #schedule: schedule,
            },
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i19.ScheduledStatus>>);

  @override
  _i4.Future<_i2.MastodonResponse<_i7.Empty>> destroyScheduledStatus(
          {required String? statusId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #destroyScheduledStatus,
          [],
          {#statusId: statusId},
        ),
        returnValue: _i4.Future<_i2.MastodonResponse<_i7.Empty>>.value(
            _FakeMastodonResponse_0<_i7.Empty>(
          this,
          Invocation.method(
            #destroyScheduledStatus,
            [],
            {#statusId: statusId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MastodonResponse<_i7.Empty>>.value(
                _FakeMastodonResponse_0<_i7.Empty>(
          this,
          Invocation.method(
            #destroyScheduledStatus,
            [],
            {#statusId: statusId},
          ),
        )),
      ) as _i4.Future<_i2.MastodonResponse<_i7.Empty>>);
}
