flutter build apk --dart-define=MASTODON_DEFAULT_INSTANCE_BEARER_TOKEN=iPzO05ExfKNUWs9qZXQztKFtSBvH_8VpX5HBbNvfBBo \
	--dart-define=MASTODON_DEFAULT_INSTANCE_CLIENT_SECRET=G9s8ab24lzFYb8ST2NUuFB-SD7sI1FriwVUCM_AMPjg \
	--dart-define=TEST_INTEGRATION=FALSE \
	--dart-define=MASTODON_DEFAULT_INSTANCE_DOMAIN=mastodon.andymcdowall.com \
	--dart-define=MASTODON_DEFAULT_INSTANCE_CLIENT_ID=viExl3ET3U1wrFFznxp8Yy_m6jHx-6nbY7NR8eT-abQ \

